# Miscelaneous
favicon: /favicon.ico

# main menu navigation
# ====================================
menu:
  home: /
  archive: /archives
  #tags: /tags
  about: /about

# site logo introduce and footer quote
# ====================================
logo:
introduce:
quote:

# social club
# ====================================
social:
  zhihu:
  weibo:
  github:
  steam:
  linkedin:
  facebook:
  twitter:
  douban:
  tumblr:
  instagram:
  stackoverflow:

# third party services settings
# ===================================

#leanCloud
leancloud:
  app_id:
  app_key:


#disqus
disqus_shortname:

#changyan
changyan:
  appid:
  appkey:

# ==================================

# ==================================
