# Miscelaneous
favicon: /favicon.ico

# fancybox gallery
fancybox: true

# main menu navigation
# ====================================
menu:
  home: /
  archive: /archives
  #tags: /tags
  about: /about

# site logo introduce and footer quote
# ====================================
logo: Ztopic
introduce: "practice makes perfect"
quote: "Love all, trust a few, do wrong to none.——William Shakespeare"

# social club
# ====================================
social:
  zhihu: https://www.zhihu.com/
  weibo: https://weibo.com
  github: https://github.com/
  steam:
  linkedin:
  facebook:
  twitter:
  douban:
  tumblr:
  instagram:
  stackoverflow:
  rss: 

# third party services settings
# ===================================

#leanCloud
leancloud:
  app_id:
  app_key:


#disqus
disqus_shortname:


# ==================================
version: 1.0
# ==================================
