# Miscelaneous
favicon: /favicon.ico

# main menu navigation
# ====================================
menu:
  home: /
  archive: /archives
  #tags: /tags
  about: /about

# site logo introduce and footer quote
# ====================================
logo: Zcc's blog
introduce: "practice makes perfect"
quote: "草在结它的种子，风在摇它的叶子。我们站着，不说话，就十分美好。——顾城《门前》"

# social club
# ====================================
social:
  zhihu: https://www.zhihu.com/people/zao-gao-tou-ding
  weibo: http://weibo.com/u/5629747157
  github: https://github.com/wa-ri
  steam:
  linkedin:
  facebook:
  twitter:
  douban:
  tumblr:
  instagram:
  stackoverflow:

# third party services settings
# ===================================

#leanCloud
leancloud:
  app_id: 7ieEM5Wg1VoXasvlhdlNIjck-gzGzoHsz
  app_key: VKmKayyxXqATSX4v3fBATw7U


#disqus
disqus_shortname: wa-ri-github-io

#changyan
changyan:
  appid:
  appkey:

# ==================================
version: 1.0
# ==================================
